import asyncio
from tracemalloc import start
import httpx
import time

async def fetch_length(client, url):
    """MAP function: fetch a URL and return its content length."""
    resp = await client.get(url)
    return len(resp.text)

async def main():
    urls = [
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz"
    ]

    async with httpx.AsyncClient(timeout=10) as client:

        # MAP phase: run all fetches concurrently
        tasks = [fetch_length(client, url) for url in urls]
        lengths = await asyncio.gather(*tasks)

        # REDUCE phase: sum all lengths
        total_length = sum(lengths)
        print("Individual lengths:", lengths)
        print("Total length:", total_length)

start = time.perf_counter()
asyncio.run(main())
end = time.perf_counter()
print(f"Program finished in {end - start:.2f} seconds")
