import asyncio
import httpx
import time

async def fetch_length(client, url):
    resp = await client.get(url)
    return len(resp.text)

async def sequential_main():
    urls = [
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz",
        "https://hr.imv.uz",
        "https://xizmat.uzasbo.uz"
    ]
    async with httpx.AsyncClient() as client:
        lengths = []
        for url in urls:           # sequential await
            length = await fetch_length(client, url)
            lengths.append(length)

        total = sum(lengths)
        print("Sequential total length:", total)

start = time.perf_counter()
asyncio.run(sequential_main())
end = time.perf_counter()
print(f"Program finished in {end - start:.2f} seconds")